diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=you@example.com
user.name=Your Name
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
user.name=Yennifer Marcela Medrano Rodriguez
user.email=200133232+Yenni009@users.noreply.github.com
remote.origin.url=https://github.com/Yenni009/3147247-Medrano-Yennifer-fastapi-semana2.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
